### ISSUE TITLE
solution for using waveshare 2.13inch_e-Paper_HAT

### ISSUE THREAD

**Issue by VitaminB21** [21isenough/LightningATM#22]
Is there a solution for using this display? 

https://www.waveshare.com/wiki/2.13inch_e-Paper_HAT#Raspberry_Pi

**Comment by 21isenough** [comment]
Hey @Lace79 

No yet. But I've ordered one of these displays and am exploring it right now. Will work soon since it's a cheaper and more broadly available display. 

![Waveshare](https://i.postimg.cc/qq8r3wXX/25434ee4-62dc-443c-88a6-4a5d66073e38.jpg)

**Comment by Lace79** [comment]
Thank you! OK great, i hope it works soon. 
I tried it, but I'm still to noobie

**Comment by 21isenough** [comment]
We'll get there, yes. It's a great project to learn some more :+1:

**Comment by Lace79** [comment]
You're right, learned a lot, but now i'm lost.

**Comment by 21isenough** [comment]
Yes, now with this new E-Ink we need to add another library and quite some code to make this work.

**Comment by Lace79** [comment]
OK
I don't know if i can help, but if let me know

**Comment by 21isenough** [comment]
Working on this in a different branch here:
https://github.com/21isenough/LightningATM/tree/waveshare-screen

**Comment by FutureTravelATM** [comment]
We added the WaveShare 2.7 inch screen which works on the same libary as the Waveshare 2.13. The 2.7 does not do a partial screen refresh, so refresh is about 6 seconds....

Attached is the pinout for the screen using the included 8pin screen connector.


![WaveShare 2in7 Pinout for Raspberry Pi - 8pin connector](https://user-images.githubusercontent.com/69513231/91434600-40010f00-e88f-11ea-9169-e74ff885f96e.jpg)

**Comment by lightisfaster** [comment]
done.
