### ISSUE TITLE
Improve exchange rate calculation for currencies close to sats parity

### ISSUE THREAD

**Issue by reneaaron** [21isenough/LightningATM#60]
While building the ATM for Turkish lira during the⚡ Hackdays in Istanbul I noticed some issues due to the currently implemented rounding of exchange rates that would defraud users by up to 50% of the exchange rate.

**👀 Analysis**

The exchange rate is currently calculated as follows:

https://github.com/21isenough/LightningATM/blob/master/config.py#L193
```SATPRICE = math.floor((1 / (BTCPRICE * 100)) * 1e8)```

This means that currently you would get 1.80 sats for 1 kurus which is then rounded down to 1 sat. 

**🪲 Possible solution**

My fix was to only round the result but not the variable `SATPRICE`. 

Also the display implementations (e.g. https://github.com/21isenough/LightningATM/blob/master/displays/waveshare2in13v2.py#L449) would have to be changed to handle the increased precision.

I'll submit a PR for those changes so we can discuss them there.

**Comment by lightisfaster** [comment]
Thanks for this information. Do you still plan to submit a PR? We can test and talk about this.

**Comment by reneaaron** [comment]
Thanks for pinging me, TBH I totally forget about it 🙈 I just prepared the MR:

https://github.com/21isenough/LightningATM/pull/70/files

**Comment by AxelHamburch** [comment]
It think we can close this issue. The PR is already merged.
