### ISSUE TITLE
AttributeError: module 'requests' has no attribute 'get'

### ISSUE THREAD

**Issue by cryptopotamo** [21isenough/LightningATM#62]
Hello, 

i've followed all the steps to configure the ATM. When i execute ./app.py i recieve this error: AttributeError: module 'requests' has no attribute 'get'.

```
Traceback (most recent call last):
  File "./app.py", line 12, in <module>
    import config
  File "/home/pi/LightningATM/config.py", line 192, in <module>
    BTCPRICE = utils.get_btc_price(conf["atm"]["cur"])
  File "/home/pi/LightningATM/utils.py", line 51, in get_btc_price
    price = requests.get(
AttributeError: module 'requests' has no attribute 'get'
```
Can you help me?

Thanks

**Comment by AxelHamburch** [comment]
What did you set in the config.ini for "cur"? It should be eur or usd for the dollar.
![image](https://user-images.githubusercontent.com/84231978/158019996-01b8118b-8d76-4500-a9d1-194c0c53fe47.png)

**Comment by cryptopotamo** [comment]
I set eur. But it seems like if it cannot load the module correctly. 

`[atm]
# Set your fiat currency with the three letter
# currency code (https://www.xe.com/symbols.php)
cur = eur
`
i've found this article, but i can't solve the problem anyway: https://stackoverflow.com/questions/12258816/module-object-has-no-attribute-get-python-error-requests

**Comment by AxelHamburch** [comment]
Did you do the last point `pip3 install -r requirements.txt` too?
![image](https://user-images.githubusercontent.com/84231978/158020345-d6c42ff9-dc95-4ee9-9d9a-0b0b0f0b8590.png)

**Comment by AxelHamburch** [comment]
https://github.com/21isenough/LightningATM/blob/master/docs/guide/sdcard_and_wifi.md#perform-an-update-clone-the-atm-github-and-install-necessary-additional-options

**Comment by cryptopotamo** [comment]
Yes, i've done also that. 
So, i want to try to reset all and try again from the first step.
Maybe i've done something wrong at the beginning.

**Comment by AxelHamburch** [comment]
Ok, can happen! But it looks like the module 'requests' is not updatet with the `pip3 install -r requirements.txt` correctly. Because there it will be updatet. Maybe you have been in the wrong directory if you set the command. Do `cd ~/LightningATM` bevor you start the `pip3 install -r requirements.txt`. You can also run the command again. Then you will see whether he has to install something or already had everything.

**Comment by AxelHamburch** [comment]
This is a correct first execution with the orignal image from 2019.

![image](https://user-images.githubusercontent.com/84231978/158021424-e4b7751c-f4ef-4e61-add5-8907bf3b95ae.png)

**Comment by cryptopotamo** [comment]
Thank you very much. 
I'll try again and let you know.


> This is a correct first execution with the orignal image from 2019.
> 
> ![image](https://user-images.githubusercontent.com/84231978/158021424-e4b7751c-f4ef-4e61-add5-8907bf3b95ae.png)

**Comment by cryptopotamo** [comment]
So, i've formatted everything and reinstalled. 
Now it works like a charm. :) 

Thanks for the help anyway!
