### ISSUE TITLE
Delete possible error as is already patched at the beginning of the article

### ISSUE THREAD

**Issue by danielcharrua** [21isenough/LightningATM#82]
I think we can delete this part as nobody will install the Waveshare lib and it lets to confusion.

If you follow the article and instal the compatible library (https://github.com/AxelHamburch/e-Paper/) you are not going to see the `spidev` error on screen, so I would delete it to make it more clear.

https://github.com/21isenough/LightningATM/blob/b9ba6bb259ab4266a7b588b2fb5abafb310f7da7/docs/guide/display.md?plain=1#L35C1-L52C1

**Comment by AxelHamburch** [comment]
I would not delete that. Some have already fallen into the trap and this is the hint and he way out. If someone does everything right, he simply does not need this hint, because he does not get an error message.

**Comment by danielcharrua** [comment]
ok, no problema... closing issue.
